---
root: true
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - airbnb
  - airbnb/whitespace
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
  - prettier/@typescript-eslint
  - prettier/react
  - preact
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - import
  - react
  - react-hooks
  - prettier
settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    typescript: {}
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "**/*.test.{ts,tsx}"
  import/prefer-default-export: off
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - unknown
  import/no-duplicates: off
  no-duplicate-imports: error
  no-useless-constructor: off
  prefer-const:
    - error
    - destructuring: all
  spaced-comment:
    - error
    - always
    - markers:
        - /
  '@typescript-eslint/prefer-optional-chain': error
  '@typescript-eslint/no-useless-constructor': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: none
      ignoreRestSiblings: true
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  react/jsx-props-no-spreading: off
  react/destructuring-assignment: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: off
